export default function DeploymentDocsPage() {
  return (
    <>
      <h1 className="text-4xl font-light tracking-tight mb-4">Static Deployment</h1>
      <p className="text-gray-500 dark:text-gray-400 mb-12 text-lg">
        Dboke's frontend is fully optimized for static exports (`output: export`). When built, it generates a production-ready static HTML bundle in the `apps/web/out` directory that can be hosted on any static web server.
      </p>

      <section className="space-y-8">
        <div>
          <h2 className="text-2xl font-medium tracking-tight mb-3 flex items-center gap-2">
            <span className="text-blue-500 text-3xl">🌐</span> NGINX Configuration
          </h2>
          <div className="p-6 rounded-xl border border-gray-200 dark:border-gray-800 bg-gray-50/50 dark:bg-gray-900/30">
            <p className="text-gray-600 dark:text-gray-400 mb-4">
              Next.js static exports drop the `.html` extension in URLs. Add this configuration to your NGINX server block so it resolves the paths correctly:
            </p>
            <pre className="p-4 bg-black text-green-400 rounded-md overflow-x-auto text-sm font-mono shadow-inner border border-gray-800">
{`server {
    listen 80;
    server_name dboke.example.com;
    
    # Point this to the 'out' directory generated by Next.js
    root /path/to/dboke/apps/web/out;
    index index.html;

    location / {
        # Try finding the exact file, then append .html, then directory, or 404
        try_files $uri $uri.html $uri/ =404;
    }

    # Optional: Cache static assets (CSS, JS, Fonts)
    location ~* \.(?:css|js|woff2?|svg|png|jpg|jpeg|gif|ico)$ {
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
    }
}`}
            </pre>
          </div>
        </div>

        <div>
          <h2 className="text-2xl font-medium tracking-tight mb-3 flex items-center gap-2">
            <span className="text-red-500 text-3xl">🪶</span> Apache Configuration
          </h2>
          <div className="p-6 rounded-xl border border-gray-200 dark:border-gray-800 bg-gray-50/50 dark:bg-gray-900/30">
            <p className="text-gray-600 dark:text-gray-400 mb-4">
              If you are deploying on an Apache server, create an `.htaccess` file inside the `apps/web/out` folder to handle extensionless HTML routing:
            </p>
            <pre className="p-4 bg-black text-green-400 rounded-md overflow-x-auto text-sm font-mono shadow-inner border border-gray-800">
{`<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /

    # If the requested URL is not a directory
    RewriteCond %{REQUEST_FILENAME} !-d
    # And if the URL + .html exists as a file
    RewriteCond %{REQUEST_FILENAME}.html -f
    # Rewrite the URL to append .html internally
    RewriteRule ^(.*)$ $1.html [L]
</IfModule>

# Optional: Add caching headers for static assets
<IfModule mod_expires.c>
    ExpiresActive On
    ExpiresByType text/css "access plus 1 year"
    ExpiresByType application/javascript "access plus 1 year"
    ExpiresByType image/svg+xml "access plus 1 year"
</IfModule>`}
            </pre>
          </div>
        </div>
      </section>
    </>
  );
}
